name: learn_ai

description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  cloud_firestore: ^4.8.5
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.3.3
  dots_indicator: ^3.0.0
  firebase_auth: ^4.7.3
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_easyloading: ^3.0.5
  flutter_screenutil: ^5.8.4
  fluttertoast: ^8.2.2
  intl: ^0.18.1
  shared_preferences: ^2.2.1
  shimmer: ^3.0.0
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir-Book.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
